### ISSUE TITLE
Area + club should be able to create / delete persons

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#149]

**Comment by tjnurmin** [comment]
Waiting for confirmation if 2nd level view is not allowed to do this.

**Comment by tjnurmin** [comment]
2nd level must be allowed to do this too

**Comment by rrimpila** [comment]
Areas and clubs are now able to add members. The form forces them to add the member directly to a group, otherwise they would be unable to access the member later.

This also makes removing tricky, since members cannot be removed if they belong to a group, but if a club removes the member from each group, the club will no longer be able to access the data for that member. Does the 'set removed' work when member is still in a group?

**Comment by rrimpila** [comment]
Allowed removing member if he belongs only to groups on the organization level. (Should the member belong to groups in suborganization within the current organization, those connections still need to be removed first)

**Comment by tjnurmin** [comment]
Will create cron to remove unnecessary connections.
